proj21j/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from myapp import views
app_name='first'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
url(r'^home/', include('myapp.cont')),
url(r'^$',views.first),
url(r'^login/',views.login),
url(r'^signup/',views.signup),
url(r'^logout/',views.logout),
]

myapp/models.py
from django.db import models

class  Core(models.Model):
    R_loc=models.CharField(max_length=100)

    def __str__(self):
        return "location   "+self.R_loc

class Rest(models.Model):
    loc=models.ForeignKey(Core,on_delete=models.CASCADE)

    Rname=models.CharField(max_length=500)
    Rimg=models.CharField(max_length=1000)
    rating=models.IntegerField(default=0)
    usrrating=models.FloatField(default=0.0)
    review=models.TextField(max_length=1000)
    catg=models.CharField(max_length=500)

    def __str__(self):
        return "name: "+self.Rname+" categ:"+self.catg
class Menu(models.Model):
    m_rest=models.ForeignKey(Rest,on_delete=models.CASCADE)
    mcatg=models.CharField(max_length=100)
    mtitle=models.CharField(max_length=500)
    mprice=models.FloatField(default=0.0)
    mimg=models.CharField(max_length=1000)

    def __str__(self):
        return "menu  " + self.mtitle+" categ:"+self.mcatg

class Order(models.Model):
    o_id=models.ForeignKey(Menu,on_delete=models.CASCADE)
    o_qt=models.IntegerField(default=0)
    pay=models.IntegerField(default=0)
    d_time=models.DateTimeField(default=None)
    user_name=models.CharField(max_length=100)

    def __str__(self):
        return ' orderid'+str(self.id)

myapp/views.py
from django.contrib.auth.forms import UserCreationForm
from datetime import datetime
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Core,Rest,Menu,Order
from .form import LoginForm,OrderForm
from django.contrib.auth import authenticate


def login(request):
    #message="alert('you successfully login')"
    if request.method=='POST':
        myloginform=LoginForm(request.POST)
        if myloginform.is_valid():
            usern = myloginform.cleaned_data.get("username")
            passw = myloginform.cleaned_data.get("password")



            user = authenticate(username=usern, password=passw)
            if user is not None:
                request.session['username'] = usern
                nu=len(Order.objects.filter(user_name=user))
                request.session['ordernumber']=nu
                try:
                    oid=request.session["orderid"]
                except:

                    return redirect("/home/")
                else:
                    del request.session["orderid"]

                    return redirect("/home/rpage/order/"+str(oid))
    else:
        myloginform=LoginForm()
    return render(request,"myapp/login.html",{"form":myloginform})

def home(request):
    a=Core.objects.all()
    try:
        user=request.session["username"]
        num=request.session["ordernumber"]
    except:
        return render(request,"myapp/home.html",{"location":a})
    else:
        return render(request, "myapp/home.html", {"location": a,'user':user,'number':num})


def resturant(request,rid):
    a=Core.objects.get(id=rid)
    try:
        user = request.session["username"]
        num = request.session["ordernumber"]
    except:
        return render(request, "myapp/rest.html", {'Restu': a})
    else:
        return render(request, "myapp/rest.html", {'Restu': a, 'user': user, 'number': num})



def rmenu(request,mid):
    x=Rest.objects.get(id=mid)
    try:
        user = request.session["username"]
        num = request.session["ordernumber"]
    except:
        return render(request, "myapp/menupage.html", {'menusample': x})
    else:
        return render(request, "myapp/menupage.html", {'menusample': x, 'user': user, 'number': num})



def orderpage(request,oid):
    request.session["orderid"]=oid
    doneorder=False
    num=0
    user=''
    try:
        user=request.session["username"]
        num = request.session["ordernumber"]
    except:
        return redirect("/login/")
    else:
        m=Menu.objects.get(id=oid)
        if request.method=='POST':
            myform=OrderForm(request.POST)
            if myform.is_valid():
                oqty=myform.cleaned_data.get("qty")
                opay=m.mprice*oqty
                query=Order.objects.create(o_id=m,o_qt=oqty
                                     ,pay=opay,
                                     d_time=datetime.now(),
                                     user_name=user)
                query.save()
                doneorder=True

        else:
            myform=OrderForm()
        return render(request,"myapp/orderpage.html",
                      {"menu":m,"form":myform,"status":doneorder,'user':user,'number':num})

def cart(request):
    request.session["cartpage"]=True
    try:
       user = request.session["username"]
    except:
        return redirect("/login/")
    else:
        orders = Order.objects.filter(user_name=user)
        payment=sum(x.pay for x in orders)
        payment=payment+payment*0.18
        return render(request,"myapp/cart.html",{"orders":orders,"pay":payment})

def payment (request):
    add=request.POST.get("address1",False)
    add2=request.POST.get("address2",False)
    pay=request.POST.get("pay",False)
    if add!=False and add2!=False :
        if pay=='card':
            "payment gateway"
        if pay=='cod':
            return render(request,"myapp/cod.html",{"add":add+','+add2})
    else:
        pass
    return render(request,"myapp/pay.html")

def cartdelete(request,cid):
   Order.objects.filter(id=cid).delete()
   return redirect("myapp:cartpage")

def paymentgateway (request):
    return HttpResponse("<h>on payment page</h>")

def signup(request):
    if request.method=="POST":
        form=UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            susername=form.cleaned_data.get('username')
            spassword=form.cleaned_data.get("password1")
            user=authenticate(username=susername,password=spassword)
            return redirect("/login/")
    else:
        form=UserCreationForm()
    return render(request,"myapp/signup.html",{"form":form})

def logout(request):
    del request.session["username"]
    return redirect("/login/")

def first(request):
    return render(request,"myapp/default.html")

myapp/templates/myapp/cart.html
{% extends 'myapp/master.html' %}
{% block title %}MyCart{% endblock %}
{% block body %}

 <div class="row">
 {% for i in orders %}
    <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
    <img src="{{ i.o_id.mimg }}" alt="Sandwich" style="width:100%">
    <div class="caption">
    <h1>DISH:{{ i.o_id.mtitle }}</h1>
     <p>quantity:{{ i.o_qt }}</p>
     <h4>Price: {{ i.pay }}</h4>
        <center><p><a href="{% url "myapp:cartdeletepage" i.id %}" class="btn btn-primary" role="button">
         <span class="glyphicon glyphicon-trash" > Delete
         </span></a>
        </p></center>
     </div>
    </div>
  </div>
 {% endfor %}
 </div>
    <center>
    <h1>Total(inclusive of GST @18%) :<b>{{pay}}</b></h1>
        <p><a href="{% url 'myapp:pay' %}" class="btn btn-primary" role="button">
         <span class="glyphicon glyphicon-ok" > Confirm
         </span></a></center>
{% endblock %}

myapp/templates/myapp/cod.html
{% extends 'myapp/master.html' %}
{% block title %}Recipt{% endblock %}
{% block body %}
    <h1>Thank You For Using Khana Khazana</h1>
    <h2>Address:{{ add }}</h2>
    <center><p><a href="{% url "myapp:home"%}" class="btn btn-primary" role="button">
         <span class="glyphicon glyphicon-home" > home
         </span></a>
        </p></center>

{% endblock %}

myapp/templates/myapp/default.html
{% extends 'myapp/master.html' %}
{%block title  %}Locations{% endblock %}
{% block body %}
<!-- Header -->
<header class="w3-display-container w3-content w3-wide" style="max-width:1600px;min-width:500px" id="home">
  <img class="w3-image" src="https://www.w3schools.com/w3images/hamburger.jpg" alt="Hamburger Catering" width="1600" height="800">
  <div class="w3-display-bottomleft w3-padding-large w3-opacity">
    <h1 class="w3-xxlarge">Le Catering</h1>
  </div>
</header>

<!-- Page content -->
<div class="w3-content" style="max-width:1100px">

  <!-- About Section -->
  <div class="w3-row w3-padding-64" id="about">
    <div class="w3-col m6 w3-padding-large w3-hide-small">
     <img src="https://www.w3schools.com/w3images/tablesetting2.jpg" class="w3-round w3-image w3-opacity-min" alt="Table Setting" width="600" height="750">
    </div>

    <div class="w3-col m6 w3-padding-large">
      <h1 class="w3-center">About Khana Khazana</h1><br>
      <h5 class="w3-center">Tradition since 1889</h5>
      <p class="w3-large">The Catering was founded in blabla by Mr. Smith in lorem ipsum dolor sit amet, consectetur adipiscing elit consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute iruredolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.We only use <span class="w3-tag w3-light-grey">seasonal</span> ingredients.</p>
      <p class="w3-large w3-text-grey w3-hide-medium">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod temporincididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
  </div>

  <hr>

  <!-- Menu Section -->
  <div class="w3-row w3-padding-64" id="menu">
    <div class="w3-col l6 w3-padding-large">
      <h1 class="w3-center">Our Menu</h1><br>
      <h4>Bread Basket</h4>
      <p class="w3-text-grey">Assortment of fresh baked fruit breads and muffins 5.50</p><br>

      <h4>Honey Almond Granola with Fruits</h4>
      <p class="w3-text-grey">Natural cereal of honey toasted oats, raisins, almonds and dates 7.00</p><br>

      <h4>Belgian Waffle</h4>
      <p class="w3-text-grey">Vanilla flavored batter with malted flour 7.50</p><br>

      <h4>Scrambled eggs</h4>
      <p class="w3-text-grey">Scrambled eggs, roasted red pepper and garlic, with green onions 7.50</p><br>

      <h4>Blueberry Pancakes</h4>
      <p class="w3-text-grey">With syrup, butter and lots of berries 8.50</p>
    </div>

    <div class="w3-col l6 w3-padding-large">
      <img src="https://www.w3schools.com/w3images/tablesetting.jpg" class="w3-round w3-image w3-opacity-min" alt="Menu" width="500" height="750">
    </div>
  </div>

  <hr>

  <!-- Contact Section -->
  <div class="w3-container w3-padding-64" id="contact">
    <h1>Contact</h1><br>
    <p>We offer full-service catering for any event, large or small. We understand your needs and we will cater the food to satisfy the biggerst criteria of them all, both look and taste. Do not hesitate to contact us.</p>
    <p class="w3-text-blue-grey w3-large"><b>Catering Service, All Over India</b></p>
    <p>You can also contact us by phone XXXXXXXXX or email Khana@Khzana.com, or you can send us a message here:</p>
  </div>
<!-- End page content -->
</div>

<!-- Footer -->

{% endblock %}

myapp/templates/myapp/home.html
{% extends 'myapp/master.html' %}
{%block title  %}Locations{% endblock %}
{% block body %}
    {% if user %}
    {% block user %}{{ user }}{% endblock %}
    {% endif %}
    {% if number %}
    {% block number %}{{ number}}{% endblock %}
    {% endif %}

    <div class="row">

{% for i in location %}
    <div class="col-xs-6 col-md-4">
    <div class="jumbotron">
  <h1><a href="/home/{{ i.id }}">{{ i.R_loc }}</a> </h1><br>
  <p>Enjoy the vibrant dishes of{{ i.R_loc  }}</p>
  <p><a class="btn btn-primary btn-lg" href="/home/{{ i.id }}"
        role="button">Resturants</a></p>
</div></div>
 {% endfor %}

    </div>
{% endblock %}

myapp/templates/myapp/login.html
{% extends 'myapp/master.html' %}
{% block title %}LOGIN{% endblock %}
{% block body %}

   <center>


         <div class="thumbnail" style="background-color: ghostwhite">
         <img src="http://trak.in/wp-content/uploads/2010/12/Khana-Khazaana.jpg" class="w3-circle" alt="Norway">
         <form method="post" action="" enctype="multipart/form-data">
       {% csrf_token %}

       {% for el in form %}
        <span >{{ el.errors }}</span>
        <label ><h3 style="background-color: aquamarine">{{ el.label_tag }}{{ el }}</h3></label>

        <br>
        {% endfor %}
        <input type="submit" id="msg" onclick="{{ message }}"value=" login" style="width: 150px; background-color: lime; padding-left: 8px; padding-top: 8px; padding-bottom: 8px; height: 30px">
        </form>
      </div></center>
{% endblock %}

myapp/templates/myapp/master.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?
family=Karma">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
.w3-bar-block .w3-bar-item {padding:20px}
</style>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color: whitesmoke">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://127.0.0.1:8000/"><span class="glyphicon glyphicon-cutlery" aria-hidden="true">KHANA KHAZANA</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'myapp:home' %}"><span class="glyphicon glyphicon-hand-right" aria-hidden="true"> Location</span> <span class="sr-only">(current)</span></a></li>

      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/login/"><span class="glyphicon glyphicon-log-in" aria-hidden="true">Login</span></a></li>
        <li><a href="/signup/"><span class="glyphicon glyphicon-plus" aria-hidden="true">SignUp</span></a></li>
        <li><a href="/logout/"><span class="glyphicon glyphicon-log-out" aria-hidden="true">Logout</span></a></li>
        <li><a href="{% url 'myapp:cartpage' %}"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true">&nbsp;{% block number %}{% endblock %}Mycart</span></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<h1>User: {% block user %} {% endblock %}</h1>
{% block body %}
{% endblock %}
<footer class="w3-center w3-light-grey w3-padding-32">
  <p>Credits Cetpa Infotech Students</p>
</footer>
</body>
</html>

myapp/templates/myapp/menupage.html
{% extends 'myapp/master.html' %}
{% block title %}{{ menusample.Rname }}{% endblock %}
  {% if user %}
    {% block user %}{{ user }}{% endblock %}
    {% endif %}
    {% if number %}
    {% block number %}{{ number}}{% endblock %}
    {% endif %}

{% block body %}
    <div class="row">
    {% for i in menusample.menu_set.all %}
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <a href="/home/rpage/order/{{ i.id }}" class="thumbnail">
      <img src="{{ i.mimg }}" alt="Sandwich" style="width:100%">
  </a>
      <div class="caption">
        <h1>DISH:{{ i.mtitle }}</h1>
     <p>Category:{{ i.mcatg }}</p>
     <h4>Price: {{ i.mprice }}</h4>
     <p><a href="/home/rpage/order/{{ i.id }}" class="btn btn-primary" role="button">order</a>
     </p>
      </div>
    </div>
  </div>
   {% endfor %}
</div>
 <!-- About Section -->
  <div class="w3-container w3-padding-32 w3-center">
    <h3>About Me, The Food Man</h3><br>
    <img src="{{ menusample.Rimg }}" alt="Me" class="w3-image" style="display:block;margin:auto"  height="100">
    <div class="w3-padding-32">
      <h4><b>{{ menusample.Rname }}</b></h4>
      <h6><i>With Passion For Real, Good Food</i></h6>
      <p>Just me, myself and I, exploring the universe of unknownment. I have a heart of love and an interest of lorem ipsum and mauris neque quam blog. I want to share my world with you. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
    </div>
  </div>
{% endblock %}

myapp/templates/myapp/orderpage.html
{% extends 'myapp/master.html' %}
{% block title %}order{% endblock %}
{% block body %}
  {% if user %}
    {% block user %}{{ user }}{% endblock %}
    {% endif %}
    {% if number %}
    {% block number %}{{ number}}{% endblock %}
    {% endif %}

 <div class="row">
 <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
    <img src="{{ menu.mimg }}" alt="Sandwich" style="width:100%">
    <div class="caption">
    <h1>DISH:{{ menu.mtitle }}</h1>
     <p>Category:{{ menu.mcatg }}</p>
     <h4>Price: {{ menu.mprice }}</h4>
     </div>
    </div>
  </div>
 </div>
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {% for el in form %}
        <span >{{ el.errors }}</span>
        <label>{{ el.label_tag }}</label>
        {{ el }}
        <br>
    {% endfor %}
<input type="submit" value="order">
</form>
    {% if status %}
    <h2>order done wana repeat a order </h2>
     {% else %}
    <h2>place a order</h2>
    {% endif %}
{% endblock %}

myapp/templates/myapp/pay.html
{% extends 'myapp/master.html' %}
{% block title %}Payment{% endblock %}
{% block body %}
  <form action="{% url 'myapp:pay' %}" method="post">
   {% csrf_token %}
      <div class="form-group">
    <label for="address1">house number/street</label>
    <input type="text" class="form-control" id="address1" placeholder="address1" name="address1">
  </div>
  <div class="form-group">
    <label for="address2">City/District</label>
    <input type="text" class="form-control" id="address2" placeholder="address2" name="address2">
  </div>

        <input type="radio" id="pay{{ forloop.counter }}" name="pay" value="cod">
        <label for="pay{{ forloop.counter }}">
            COD
        </label></br>
        <input type="radio" id="pay{{ forloop.counter }}" name="pay" value="card">
        <label for="pay{{ forloop.counter }}">
            Payment Gateway
        </label></br>

  <button type="submit" class="btn btn-default">Submit</button>
</form>
    <div style="background-color:#7ceab3" class="jumbotron">
  <h1><span class="glyphicon glyphicon-cutlery">Khana Khazana</span> </h1>
  <h6><i>With Passion For Real, Good Food</i></h6>
      <p>Just me, myself and I, exploring the universe of unknownment. I have a heart of love and an interest of lorem ipsum and mauris neque quam blog. I want to share my world with you. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>

  </div>
{% endblock %}

myapp/templates/myapp/rest.html
{% extends 'myapp/master.html' %}
{% block title %}RESTAURANT{% endblock %}
{% block body %}
      {% if user %}
    {% block user %}{{ user }}{% endblock %}
    {% endif %}
    {% if number %}
    {% block number %}{{ number}}{% endblock %}
    {% endif %}

    <div class="row">
    {% for i in Restu.rest_set.all %}
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <a href="/home/rpage/{{ i.id }}" class="thumbnail">
      <img src="{{ i.Rimg }}" alt="NOt AVAILABLE" height="100" >
     </a>
      <div class="caption">
        <h1><a href="/home/rpage/{{ i.id }}">{{ i.Rname }}</a> </h1><br>
     <p>Category:{{ i.catg }}</p>
     <h3>Rating:{{ i.rating }}</h3>
     <h4>user rating: {{ i.userrating }}</h4>
     <h5>review:{{ i.review }}</h5>
        <p><a href="/home/rpage/{{ i.id }}" class="btn btn-primary" role="button">view</a>
        <a href="#" class="btn btn-default" role="button">review</a></p>
      </div>
    </div>
  </div>
   {% endfor %}
</div>
{% endblock %}

myapp/templates/myapp/signup.html
{% extends 'myapp/master.html' %}
{% block title %}signup{% endblock %}
{% block body %}


   <center>


      <div class="thumbnail" style="background-color: ghostwhite">
      <img src="http://trak.in/wp-content/uploads/2010/12/Khana-Khazaana.jpg" class="w3-circle" alt="Norway">
      <form method="post" action="" enctype="multipart/form-data">
       {% csrf_token %}

       {% for el in form %}
        <span >{{ el.errors }}</span>
        <label ><h3 style="background-color: aquamarine">{{ el.label_tag }}{{ el }}</h3></label>

        <br>
        {% endfor %}
        <input type="submit" value="signup" style="width: 150px; background-color: lime; padding-left: 8px; padding-top: 8px; padding-bottom: 8px; height: 30px">
        </form>
      </div></center>
{% endblock %}}